import type { Protocol } from 'puppeteer'

export type PuppeteerCookie = Protocol.Network.CookieParam

export function parseCookiesJson(input: string): PuppeteerCookie[] {
  const data: unknown = JSON.parse(input)
  if (!Array.isArray(data)) return []
  return data
    .filter((c): c is Record<string, unknown> => typeof c === 'object' && c !== null)
    .filter((c) => typeof c.name === 'string' && typeof c.value === 'string')
    .map((c) => c as unknown as PuppeteerCookie)
}

export function cookiesToNetscape(cookies: PuppeteerCookie[]): string {
  const header = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by ThreatBrowser',
    '# https://curl.se/docs/http-cookies.html',
    ''
  ].join('\n')

  const lines = cookies.map((c) => {
    const domain = c.domain ?? ''
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expires = typeof c.expires === 'number' && c.expires > 0 ? Math.floor(c.expires) : 0
    const name = c.name
    const value = c.value
    return [domain, includeSubdomains, path, secure, expires, name, value].join('\t')
  })

  return `${header}\n${lines.join('\n')}\n`
}

export function parseCookiesNetscape(input: string): PuppeteerCookie[] {
  const lines = input
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith('#'))

  const cookies: PuppeteerCookie[] = []
  for (const line of lines) {
    const parts = line.split('\t')
    if (parts.length < 7) continue
    const [domain, , path, secureStr, expiresStr, name, value] = parts
    const secure = secureStr.toUpperCase() === 'TRUE'
    const expires = Number(expiresStr)
    cookies.push({
      domain,
      path,
      secure,
      expires: Number.isFinite(expires) ? expires : undefined,
      name,
      value
    })
  }
  return cookies
}
